### ISSUE TITLE
Using chef 13 the cookbook doesn't converge due to modification of inmutable properties

### ISSUE THREAD

**Issue by aalmenar** [chr4-cookbooks/mysqld#15]
Description

In Chef Client 13 some types of resource properties became immutable, including Hash.
         
========================================================
 Error executing action `create` on resource 'mysqld[default]'
========================================================

           RuntimeError
           ------------
           can't modify frozen Hash

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/mysqld/providers/default.rb:23:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mysqld/recipes/configure.rb

            22: mysqld 'default'
            23:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mysqld/recipes/configure.rb:22:in `from_file'

           mysqld("default") do
             action [:create]
             default_guard_interpreter :default
             declared_type :mysqld
             cookbook_name "mysqld"
             recipe_name "configure"
           end

           System Info:
           ------------
           chef_version=13.2.20
           platform=ubuntu
           platform_version=16.04
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=1615;start=13:23:26;
           executable=/opt/chef/bin/chef-client

**Comment by chr4** [comment]
Thank you for your report!

I currently only have a limited amount of time that I can dedicate to Chef-13. I'll gladly review any contributions and pull-requests on this issue, though!
