### ISSUE TITLE
Support ubuntu 16.04 xenial

### ISSUE THREAD

**Issue by aight8** [chr4-cookbooks/mysqld#5]
- systemd
- set root passwort on the new way

**Comment by chr4** [comment]
I plan to upgrade the cookook as soon as I migrate my servers.
If you have the time to fix up a pull request, I'll gladly review it!

Can you elaborate on "set root password the new way"?

**Comment by chr4** [comment]
Closing this in favor of https://github.com/chr4-cookbooks/mysqld/pull/6
