### ISSUE TITLE
Debian 8 fails to update password

### ISSUE THREAD

**Issue by aalmenar** [chr4-cookbooks/mysqld#9]
When using the default mysql (At this time 5.5.52 on debian 8) password doesn't get updated and mysql root user remains without password.

Updating authentication_string has no effect on this version. Searching over the web found the following:

MySQL 5.7.5 and earlier version:
SET PASSWORD FOR 'user_name' = PASSWORD('new_password');

MySQL 5.7.6 and later version:
alter user 'user_name' identified by 'new_password';

Also, the execution of the query fails with a "no database selected". fixed on a copy of the cookbook locally, but also the authentication_string also was of no effect to change the password.

**Comment by chr4** [comment]
Support for mysql < 5.7 was dropped with the cookbook version `2.0.0`.

You can either version-lock the cookbook to `~> 1.0.5` to keep using the old version, or use mysql-5.7 or mariadb 10.1 (recommended). The latter can be easily installed from the official repositories by using the `mysqld::mariadb_repository` recipe.

**Comment by chr4** [comment]
Maybe I should be more precise in the README, I wasn't aware that the `authentication_string` change was introduced between two subversions of 5.7. I was assuming the change was introduced with the version-bump from 5.6->5.7.

**Comment by Dens49** [comment]
Even though the [documentation](http://dev.mysql.com/doc/refman/5.7/en/downgrading-to-previous-series.html) that I linked to in my earlier pull request explicitly states that the change came with 5.7.6, I failed to mention that detail in my pull request. Sorry for that!

**Comment by chr4** [comment]
I added a note to the [README](https://github.com/chr4-cookbooks/mysqld#compatibility) in 612fb73ccf1188d3ecf13ddb00b9dc0dd0c5d53d

**Comment by chr4** [comment]
I believe this is the most practical approach of handling this, as supporting both generations of databases results in a lot of overhead, which will eventually faded out once migration is complete (e.g. next Debian release).

Closing this. Feel free to comment/ reopen if there's additional problems. Thanks for the report!
